#!/usr/bin/env ruby

class Pather
  attr_accessor :map, :column_start, :path_end, :no_row_path
  attr_reader :path_map, :markers, :find_char

  def initialize
    @path_map     = ""
    @find_char    = "#"
    @markers      = []
    @path_end     = nil
    @column_start = nil
    @no_row_path  = true
    f =  File.open(ARGV[0], "r")
    f.each_line {|line| path_map << line}
    @map = path_map.split("\n").map(&:chars)
    set_coordinates
  end

  def create_path
    my_path
    puts map.flat_map(&:join)
  end

  def my_path
    markers.each_with_index do |coordinates, index|
      unless markers[index + 1] == nil
        if valid_row_path?(coordinates, index)
          self.no_row_path = false
          set_row_connection(index)
          set_column_connection
        elsif valid_row_path?(coordinates, index) == false && no_row_path
          set_column_path(index)
          set_column_connection
        end
      end
    end
  end

  def valid_row_path?(coordinates, index)
    coordinates[0] == markers[index + 1][0]
  end

  def set_column_connection
    char_index = column_start[1]
    current_row_index = column_start[0]
    until current_row_index >= path_end[0]
      current_row_index += 1
      map[current_row_index][char_index] = "*"
    end
    finalize_row(current_row_index, char_index)
  end

  def set_column_path(index)
    self.column_start = markers.first
  end

  def finalize_row(row_index, char_index)
    if char_index > path_end[1]
      traverse_left(row_index, char_index)
    else
      traverse_right(row_index, char_index)
    end
  end

  def traverse_left(row_index, char_index)
    count = char_index
    until count == path_end[1]
      count -= 1
      map[row_index][count] = "*"
    end
  end

  def traverse_right(row_index, char_index)
    count = char_index
    until count == path_end[1]
      count += 1
      map[row_index][count] = "*"
    end
  end

  def set_row_connection(index)
    row      = markers[index][0]
    starting = markers[index][1]
    ending   = markers[index + 1][1]
    self.column_start = [row, ending]
    connect_row(row, starting, ending)
  end


  def connect_row(row, starting, ending)
    counter = starting
    until counter == (ending -1)
      counter += 1
      map[row][counter] = "*"
    end
  end

  def set_coordinates
    map.each_with_index do |row, index|
      if row.include?(find_char)
        row.each_with_index do |char, char_index|
          if char == find_char
            markers << [index, char_index]
            self.path_end = markers.last
          end
        end
      end
    end
  end
end

path = Pather.new
path.create_path
