#!/usr/bin/env ruby

class Pather
  attr_accessor :map
  attr_reader :path_map, :markers, :find_char

  def initialize
    @path_map  = ""
    @find_char = "#"
    @markers   = []
    f =  File.open(ARGV[0], "r")
    f.each_line {|line| path_map << line}
    @map = path_map.split("\n").map(&:chars)
    set_coordinates
  end

  def create_path
    my_path
    puts map.flat_map(&:join)
  end

  def my_path
    markers.each_with_index do |coordinates, index|
      unless markers[index + 1] == nil
        if valid_row_path?(coordinates, index)
          set_row_connection(index)
          row      = markers[index][0]
          starting = markers[index][1]
          ending   = markers[index + 1][1]
          connect_row(row, starting, ending)
        end
      end
    end
  end

  def valid_row_path?(coordinates, index)
    coordinates[0] == markers[index + 1][0]
  end

  def set_row_connection(index)
    row      = markers[index][0]
    starting = markers[index][1]
    ending   = markers[index + 1][1]
    connect_row(row, starting, ending)
  end

  def connect_row(row, starting, ending)
    counter = starting
    until counter == (ending -1)
      counter += 1
      map[row][counter] = "*"
    end
  end

  def set_coordinates
    map.each_with_index do |row, index|
      if row.include?(find_char)
        row.each_with_index do |char, char_index|
          if char == find_char
            markers << [index, char_index]
          end
        end
      end
    end
  end
end

path = Pather.new
path.create_path
